curves = [
	ce_tween_linear,
	ce_tween_quad_in,
	ce_tween_quad_out,
	ce_tween_quad_inout,
	ce_tween_cubic_in,
	ce_tween_cubic_out,
	ce_tween_cubic_inout,
	ce_tween_quart_in,
	ce_tween_quart_out,
	ce_tween_quart_inout,
	ce_tween_quint_in,
	ce_tween_quint_out,
	ce_tween_quint_inout,
	ce_tween_sin_in,
	ce_tween_sin_out,
	ce_tween_sin_inout,
	ce_tween_exp_in,
	ce_tween_exp_out,
	ce_tween_exp_inout,
	ce_tween_circ_in,
	ce_tween_circ_out,
	ce_tween_cubic_inout,
	ce_tween_back_in,
	ce_tween_back_out,
	ce_tween_back_inout,
	ce_tween_elastic_in,
	ce_tween_elastic_out,
	ce_tween_elastic_inout,
	ce_tween_bounce_in,
	ce_tween_bounce_out,
	ce_tween_bounce_inout,
];

displayed_curve = 0;

curve_timer = 0;